package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class Assignment {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing assignment Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */
					public static String assignment(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
					{
						JSONArray jsonArray =  (JSONArray)jsonObject.get("children");
						StringBuilder  sb = new StringBuilder();
						sb.append(valueMap.get(jsonArray.get(0)));
						JSONObject j =  (JSONObject) jsonObject.get("attributes");
						sb.append(j.get("operator").toString());
						sb.append(valueMap.get(jsonArray.get(1)));

						return sb.toString();
					}

}