package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class Block {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing block Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */
					public static String block(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
					{
						JSONArray jsonArray =  (JSONArray)jsonObject.get("children");
						StringBuilder sb = new StringBuilder();
						if(jsonArray==null)return sb.toString();
						sb.append("{\n");
						for(int i=0;i<jsonArray.size();i++)
						{
							sb.append(valueMap.get(jsonArray.get(i)));
							JSONObject j = (JSONObject)jsonArray.get(i);
							if(Utility.is(j.get("name").toString()))sb.append(";\n");
							else
								sb.append("\n");
						}
						sb.append("}");
						return sb.toString();
					}

				    
}