package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class IfStatement {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing ifStatement Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */
	             public static String ifStatement(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
					{
						JSONArray jsonArray = (JSONArray) jsonObject.get("children");
						StringBuilder sb = new StringBuilder();
						sb.append("if ( ");
						sb.append(valueMap.get(jsonArray.get(0))+" ) ");
						JSONObject j = (JSONObject) jsonArray.get(1);
						if(!Utility.isBlock(j.get("name").toString()))
						{
							sb.append("\n\t\t");
						}
						sb.append(valueMap.get(jsonArray.get(1)));

						if(!Utility.isBlock(j.get("name").toString()))sb.append(";");
						try
						{
							String s = valueMap.get(jsonArray.get(2));
							j = (JSONObject) jsonArray.get(2);
							sb.append("\nelse "+s);
							if(!Utility.isBlock(j.get("name").toString()) && Utility.is(j.get("name").toString()))sb.append(";");
						}
						catch(Exception e)
						{

						}
						return sb.toString();
					}
				
}