package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class ParameterList {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing parameterList Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */
			
					public static String parameterList(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
					{
						StringBuilder sb = new StringBuilder();
						JSONArray jsonArray =  (JSONArray)jsonObject.get("children");
						sb.append("(");
						for(int i = 0; i < jsonArray.size(); i++)
						{
							if(i>0)sb.append(",");
							JSONObject j1 = (JSONObject)jsonArray.get(i);
							sb.append(valueMap.get(j1));
						}
						sb.append(")");
						return sb.toString();
					}

}