package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class SourceUnit {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing sourceUnit Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node with the code  generated by them
                */
				public static String sourceUnit(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
				{
						StringBuilder sb = new StringBuilder();
						JSONObject jo = (JSONObject)jsonObject.get("attributes");
						String file_name = "output.txt"; //Assign Default file name
						try{
							file_name = jo.get("absolutePath").toString();
							PrintStream o = new PrintStream(new File(file_name)); 
							System.setOut(o); 
						}
						catch(Exception e)
						{

						}
						JSONArray jsonArray =  (JSONArray)jsonObject.get("children");
						if(jsonArray != null)
						{
							for(int i = 0; i < jsonArray.size(); i++)
							{
								JSONObject j1 = (JSONObject)jsonArray.get(i);
								sb.append(valueMap.get(j1));
							}
						}
						return sb.toString();
				}

}