package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class TupleExpression {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing TupleExpression Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */

				public static String tupleExpression(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
				{
					JSONArray jsonArray =  (JSONArray)jsonObject.get("children");
					StringBuilder sb  = new StringBuilder();
					sb.append("(");
					for(int i=0;i<jsonArray.size();i++)
					{
						if(i>0)sb.append(", ");
						sb.append(valueMap.get(jsonArray.get(i)));
					}
					sb.append(")");
					return sb.toString();
				}
				
}