package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class UnaryOperation {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing UnaryOperation Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */
	             public static String unaryOperation(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
					{
						JSONArray jsonArray = (JSONArray)jsonObject.get("children");
						StringBuilder sb = new StringBuilder();
						JSONObject j = (JSONObject)jsonObject.get("attributes");
						try
						{
							String prefix = j.get("prefix").toString();
							if(prefix.equals("true"))
							{
								sb.append(j.get("operator").toString());
								sb.append(valueMap.get(jsonArray.get(0)));
							}
							else
							{
								sb.append(valueMap.get(jsonArray.get(0)));
								sb.append(j.get("operator").toString()); 
							}
						}
						catch(Exception e)
						{
							sb.append(valueMap.get(jsonArray.get(0)));
							sb.append(j.get("operator").toString());
						}
						return sb.toString();
					}
				
}