package Nodes;
import java.io.*; 
import java.util.*;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

public class VariableDeclaration {
                /*
                     Add member variables for this class as per your needs 
                */

                /*
	                 processsing variableDeclaration Node
	                 jsonObject --> contains information of this Node 
	                 valueMap --> maps the childs of this node if it exists with the code  generated by them
                */
	                public static String variableDeclaration(JSONObject jsonObject,HashMap<JSONObject, String> valueMap)
					{
						StringBuilder sb = new StringBuilder();
						JSONObject j = (JSONObject)jsonObject.get("attributes");
						JSONArray jsonArray =  (JSONArray)jsonObject.get("children");
						if(jsonArray != null)
						{
							for(int i = 0; i < jsonArray.size(); i++)
							{
								JSONObject j1 = (JSONObject)jsonArray.get(i);
								sb.append(valueMap.get(j1));
							}
						}
						sb.append(" ");
						String storage = "";
						try{
							storage = j.get("storageLocation").toString();
						}
						catch(Exception e)
						{

						}
						if(storage.equals("default") || storage.equals(""))sb.append("");
						else sb.append(storage+" ");
						sb.append(j.get("name").toString());
						return sb.toString();
					}

				
}